### ISSUE TITLE
Wiki references undefined variable

### ISSUE THREAD

**Issue by jwpjr-dev** [jvdberg08/spigot-commandhandler#11]
**Describe The Bug**
Over [here](https://github.com/jvdberg08/spigot-commandhandler/wiki/Creating-a-custom-command-argument) on the wiki, in `UserCommandArgument#getArgument(String, Object[])`, the variable player is referenced but is never defined.

**To Reproduce**
Visit [this](https://github.com/jvdberg08/spigot-commandhandler/wiki/Creating-a-custom-command-argument) page on the wiki.

**Expected behavior**
A defined variable to be referenced, likely from the `commandArgument` parameter.

**Spigot & CommandHandler version and used branch (dev/master)**
N/A

**Do you wish to implement this bugfix yourself?**
No

**Solution**
Define the player variable, likely using `Bukkit#getPlayer(String)` in conjunction with the `commandArgument` parameter.

**Comment by jvdberg08** [comment]
Fixed the wiki! 👍
